USE [master]
GO

/****** Object:  Database [atb]    Script Date: 11/11/2020 9:11:03 AM ******/
CREATE DATABASE [atb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'atb_Data', FILENAME = N'F:\sqldata\atb_data.mdf' , SIZE = 1259072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'atb_Log', FILENAME = N'E:\sqldata\atb_log.ldf' , SIZE = 757248KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [atb] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [atb].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [atb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [atb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [atb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [atb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [atb] SET ARITHABORT OFF 
GO

ALTER DATABASE [atb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [atb] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [atb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [atb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [atb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [atb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [atb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [atb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [atb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [atb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [atb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [atb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [atb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [atb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [atb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [atb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [atb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [atb] SET RECOVERY FULL 
GO

ALTER DATABASE [atb] SET  MULTI_USER 
GO

ALTER DATABASE [atb] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [atb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [atb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [atb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [atb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [atb] SET QUERY_STORE = OFF
GO

USE [atb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [atb] SET  READ_WRITE 
GO

